### PR TITLE
bugfix(exercise-8): Header Fix Solution for Exercise 8

### PR DESCRIPTION
**Pull request by HassanAlthaf**
Try a fresh copy with no cache/state lock files and it should work.

### CODE REVIEW

**Comment by bmuschko** [comment]
Defining the provider will simply just pull down the requested version of the plugin.

```
$ terraform init
Initializing provider plugins...
- Finding hashicorp/http versions matching "3.1.0"...
- Installing hashicorp/http v3.1.0...
- Installed hashicorp/http v3.1.0 (signed by HashiCorp)
```

At this time, not defining the provider will simply pull the same version: v3.1.0.

```
$ terraform init
Initializing provider plugins...
- Finding latest version of hashicorp/http...
- Installing hashicorp/http v3.1.0...
- Installed hashicorp/http v3.1.0 (signed by HashiCorp)
```

I still get the same warning message with your change. Removing "" from the key of the map entry simply treats it the same way as a string. From the [documentation](https://www.terraform.io/language/expressions/types#maps-objects):

> The keys in a map must be strings; they can be left unquoted if they are a valid [identifier](https://www.terraform.io/language/syntax/configuration#identifiers), but must be quoted otherwise.

**Comment by HassanAlthaf** [comment]
That's weird, I'm using Terraform v1.3.2, try upgrading.

**Comment by bmuschko** [comment]
No, 1.3.2 doesn't do it either. I don't think your changes will actually fix the issue. I need to look into it separately.

**Comment by bmuschko** [comment]
FYI: It's a known issue - https://github.com/bmuschko/cta-crash-course/commit/877cdbfb4a062841179da44883a7f6a9eed6977d

**Pull request closed without merging**
